### ISSUE TITLE
Error: Illegal value for Message.Field

### ISSUE THREAD

**Issue by 100ideas** [zaim/reql-then#2]
Not sure what I'm doing wrong... could you provide some guidance?

``` bash
macowell:node_server$ npm install reql-then
|
> memcpy@0.5.0 install /Users/macowell/dev/museum/opencfu_web/node_server/node_modules/reql-then/node_modules/rethinkdb/node_modules/protobufjs/node_modules/bytebuffer/node_modules/memcpy
> node-gyp configure build

  CXX(target) Release/obj.target/memcpy/src/memcpy.o
  SOLINK_MODULE(target) Release/memcpy.node
  SOLINK_MODULE(target) Release/memcpy.node: Finished
reql-then@0.0.3 node_modules/reql-then
├── debug@0.7.4
├── generic-pool@2.0.4
├── bluebird@0.11.6
└── rethinkdb@1.11.0-4 (protobufjs@3.6.0)

macowell:node_server$ node
> var r = require('reql-then')
Error: Illegal value for Message.Field .Query.OBSOLETE_noreply of type bool: string (not a boolean)
    at Error (<anonymous>)
    at null.<anonymous> (/Users/macowell/dev/museum/opencfu_web/node_server/node_modules/reql-then/node_modules/rethinkdb/node_modules/protobufjs/dist/ProtoBuf.js:2513:27)
    at ProtoBuf.Reflect.Field.verifyValue (/Users/macowell/dev/museum/opencfu_web/node_server/node_modules/reql-then/node_modules/rethinkdb/node_modules/protobufjs/dist/ProtoBuf.js:2580:29)
    at ProtoBuf.Reflect.Field.build (/Users/macowell/dev/museum/opencfu_web/node_server/node_modules/reql-then/node_modules/rethinkdb/node_modules/protobufjs/dist/ProtoBuf.js:2479:28)
    at ProtoBuf.Reflect.Message.build (/Users/macowell/dev/museum/opencfu_web/node_server/node_modules/reql-then/node_modules/rethinkdb/node_modules/protobufjs/dist/ProtoBuf.js:2210:31)
    at ProtoBuf.Reflect.Namespace.build (/Users/macowell/dev/museum/opencfu_web/node_server/node_modules/reql-then/node_modules/rethinkdb/node_modules/protobufjs/dist/ProtoBuf.js:1500:48)
    at ProtoBuf.Builder.Builder.build (/Users/macowell/dev/museum/opencfu_web/node_server/node_modules/reql-then/node_modules/rethinkdb/node_modules/protobufjs/dist/ProtoBuf.js:3925:43)
    at Object.<anonymous> (/Users/macowell/dev/museum/opencfu_web/node_server/node_modules/reql-then/node_modules/rethinkdb/proto-def.js:973:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
> 
(^C again to quit)
> 

macowell:node_server$ node -v
v0.10.31
```

**Comment by zaim** [comment]
Hi, sorry for the lateness in reply.

I'm not sure what's happening here. But it seems to be a problem with RethinkDB. Can you try installing and requiring rethinkdb by itself, see if the same error happens:

```
$ npm install rethinkdb
$ node
> var r = require('rethinkdb');
```

I'm closing this issue for now...

**Comment by rickw** [comment]
I'm getting the same thing, I think they changed their API, I'll dig a bit deeper....

**Comment by rickw** [comment]
Ok, I discovered the overall problem, rethinkdb is at version 1.16.2 and you're requiring 1.11. Without going into your code deeply, I upgraded the version you use then I get an error that r is not defined. So it seems that reql-then needs to be updated for the version of rethinkdb.
